version: '3'

services:
    db:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: my_secret_pw
            MYSQL_DATABASE: test_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - "3306:3306"
        volumes:
            - database:/var/lib/mysql
    web:
        image: php:latest
        container_name: php_web
        depends_on:
            - db
        volumes:
            - ./php/:/var/www/html/
        ports:
            - "80:80"
        working_dir: /var/www/html/
        stdin_open: true
        tty: true
        volumes:
            - files:/var/www/html

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
            MYSQL_ROOT_PASSWORD: my_secret_pw